### ISSUE TITLE
Bots having issue accessing list from a module after installing menus on discord.py

### ISSUE THREAD

**Issue by Skyoathzero** [Rapptz/discord-ext-menus#24]
My bots worked perfectly fine before i installed menus on discord.py but after i tried to run it after installing it it give me this error
Ignoring exception in command Search:
Traceback (most recent call last):
  File "C:\Users\NABEL\PycharmProjects\pythonProject\venv\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:/Users/NABEL/PycharmProjects/pythonProject/Bot.py", line 17, in Search
    embed.add_field(name=GenshinWikiWebscrapper.var1[1], value=GenshinWikiWebscrapper.var1[2], inline=False)
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\NABEL\PycharmProjects\pythonProject\venv\lib\site-packages\discord\ext\commands\bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\NABEL\PycharmProjects\pythonProject\venv\lib\site-packages\discord\ext\commands\core.py", line 859, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\NABEL\PycharmProjects\pythonProject\venv\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: IndexError: list index out of range

**Comment by helish88** [comment]
Read your error
https://blog.finxter.com/python-indexerror-list-index-out-of-range/
