### ISSUE TITLE
New issue due to 2.0.0 issues:

### ISSUE THREAD

**Issue by JDJGInc** [Rapptz/discord-ext-menus#48]
/menus/__init__.py", line 700, in start
    permissions = channel.permissions_for(me)
AttributeError: 'PartialMessageable' object has no attribute 'permissions_for'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 960, in invoke
    await ctx.command.invoke(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 825, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 134, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'PartialMessageable' object has no attribute 'permissions_for'

**Comment by JDJGInc** [comment]
Basically I am wondering currently how I can get a PartialMessageable to become a Dmchannel again, cause otherwise I don't have a workable channel.
For anything that uses DMchannel checks for me.
